### PR TITLE
Multi Print Head Capability

### PR DESCRIPTION
**Pull request by Bjohnson131**
# How Multi-Head Processing Works

Multi-head printing loads N filaments at once and prints them in parallel, so colour changes happen at scheduled pauses rather than after every single run. Kromacut's job is to figure out the best way to group layers, assign filaments to nozzles, and arrange colors so the fewest pauses produce the most accurate result.

It runs as a post-processing pass on top of auto-paint: it takes the filament stack auto-paint already chose and reorganises it across heads. Multi-head mode and Flat Paint are mutually exclusive — turning one on turns the other off.

There are three main problems it solves, in order, plus the palette grouping that feeds them.

---

## Glossary

 - Run: a series of layers that all use the same filament.
 - Window: A group of sequential runs, typically the number of runs equals the number of nozzles.
 - DP: Dynamic programming.
 - ΔE: The ΔE between an actual and a proposed layer configuration is the difference in errorFactor between the two.
 - N: when N is referred to, you can assume that's equal to the nozzle count. Capped at 8.
 - K: the number of unique filaments in a window (K ≤ N).
 - Quality score: See ΔE
 - ErrorFactor: The difference between the desired color, and the actual color that a series of layers will produce. Always a positive value, or 0.

---

## 1. Grouping Layers into Windows

Instead of swapping filament for every color change, the printer batches N consecutive color regions into a "window" and handles them all with the same N loaded filaments. It only pauses at window boundaries.

Before windows can be defined, Kromacut builds a **run stack** — a list of contiguous layer blocks where each block uses one filament. Colors are mapped to print heights by luminance (brighter = higher), then the full layer sequence is expanded at the printer's actual layer height. Where the filament index changes between layers, a new run starts.

01_window_run_diagram

**Under the hood:** selecting which runs become windows isn't just "take the first N, then the next N." Kromacut runs a dynamic programming pass over all candidate windows to find the non-overlapping subset that maximises a cumulative quality score. Each window gets an `errorFactor` — how well its N filaments cover the colours in that band — and the DP finds the combination of windows that maximises the total. Because windows are fixed-width (always N runs), the DP is O(n): the best previous non-overlapping window is always exactly N steps back, so there's no backtracking. The search also stops early once no remaining window improves the score by more than 0.01% — no point squeezing out tiny gains near the bottom of the pile. It will also end if no windows of >1 run long can be constructed.

Runs that don't land in any selected window are **unclaimed** and print with whatever filament was last loaded.

The head count N is limited to **8**. The per-window search below costs K^N, which reaches ~16.7M at 8 heads; the limit keeps a build bounded, and requests above it are clamped.

---

## 2. Assigning Filaments to Nozzles

Once windows are chosen and arranged appropriately, each window needs a filament assigned to each of its N nozzle slots. The goal is to match the target colors as closely as possible while reusing filaments across windows to minimize swaps.

02_nozzle_swap_schedule

**Under the hood:** this is split into two stages.

*Stage 1 — what goes in each slot.* For every window, Kromacut scores filament-per-slot orderings and keeps the best. The score is a perceptual color difference (more on that below) weighted by how many pixels in the frame use each color, so dominant colors matter more than rare ones. The space of orderings is K^N. When that fits inside the search-depth tier's budget the scan is exhaustive; when it doesn't, the scan evaluates a **fixed, evenly-spaced deterministic sample** of that many orderings instead — plus the window's current ordering, so a sampled scan can't do worse than leaving the window alone. There is no randomness, so rebuilding with the same inputs gives the same result.

*Stage 2 — linking windows together.* The per-window assignments are then threaded across the full print with a second DP. The state at each step is the N-tuple of currently loaded filament IDs. Moving from one window to the next costs one swap per nozzle slot that changes filament; idle slots carry their previous filament for free. The DP finds the sequence of assignments that minimises total swaps across the whole print.

One extra detail: individual runs inside a window can override the window-level consensus if a per-run slot assignment scores better. This lets two adjacent color regions in the same window use slightly different arrangements without forcing a full nozzle change.

If no window ends up beating the plain stack — or the background worker fails — the build falls back to a normal single-head model and says so. It never emits a multi-head file with guessed head assignments.

---

## 3. Scoring Color Accuracy

FDM filaments are semi-translucent, so the color you see on a print isn't just the top filament — it's a blend of everything light passes through on its way in and out. The order filaments are stacked in directly changes the perceived color.

03_beer_lambert_blending

**Under the hood:** Kromacut models light transmission with:

```
T = 0.1 ^ (thickness / TD)
```

`TD` is the filament's transmission distance — the depth at which 10% of light still passes through. At one TD of thickness, 90% is absorbed; stack more layers and it drops fast. The perceived color at each depth is composited as:

```
result = filament_color × (1 − T) + background × T
```

This is evaluated layer by layer from the outside in, so the outer layers dominate and deeper layers contribute less and less.

The `TD` used here is the **frontlit hiding distance stored per filament** (profile schema v2 keeps it in `filament.td`). Multi-head consumes it through the same per-channel model as normal auto-paint — the measured R/G/B triple when the filament is calibrated, a colour-derived triple otherwise — so its blends match the rest of the pipeline. (Earlier revisions of this PR multiplied that value by 0.1 a second time inside the multi-head path; that extra scaling has been removed.)

Scoring uses **ΔE in CIE Lab space** (the CIE76 formula) rather than comparing raw RGB values. Lab is designed to match human perception, so a ΔE of 1 means a just-noticeable difference regardless of which part of the color spectrum you're in. This matters because two assignments with similar RGB error can look very different to a viewer — Kromacut optimises for what the eye sees.

---

## 4. Grouping the Palette (Color grouping)

Before the search runs, Kromacut groups the image palette into the target colours it will try to reproduce. The **Color grouping** control chooses how:

 - **Layer-based** (default, the original behaviour) — colours that map to the same print height are merged into one target. Because height comes from luminance, two colours of similar brightness but different hue collapse together, which caps the distinct-colour count near the number of printer layers.
 - **Color-based** — distinct hues stay distinct targets even when they share a height, so the optimiser can try to reproduce them separately.

Color-based removes the height-collapse bottleneck, but it is not an automatic "more colours" switch: colours only diverge from the shared stack inside a head window, so the benefit grows with head count and can be small — or occasionally negative — at low head counts. It also asks the optimiser to solve for more targets, so it costs more compute, and the group count is capped to keep the search bounded.

**Search depth** (Fast / Balanced / Thorough) moves two knobs together — how many head windows the optimiser opens, and how many filament orders it tries per window (the K^N budget from section 2). The tier labels reflect that behaviour. Search depth does **not** change which image colours are considered.

---

## Printing the Result

Multi-head mode does **not** drive physically separate extruders, and it needs **no special multi-material or N-nozzle slicer profile**.

When you build the model, Kromacut generates a **Head Schedule** in the Print Instructions panel: the filament to pre-load on each head, then a checkpoint at every layer where one or more heads change filament (only the heads that actually change are flagged; a head never used anywhere is marked EMPTY).

Export to 3MF and the checkpoints are written into the file as **pause markers** (pause / `M600`) at their layers. Slice it with your ordinary single-nozzle profile. During the print the machine pauses at each checkpoint — swap the filament on the heads flagged for that checkpoint per the schedule, then resume. Layer heights in the schedule are approximate; confirm them in your slicer before printing.

Head count, search depth, colour grouping, and the mode toggle persist with the rest of the auto-paint setup. There is a full in-app documentation page (Docs → Multi-Head Printing) with four explanatory diagrams.

### CODE REVIEW

**Comment by Bjohnson131** [comment]
@vycdev Is this PR too large?

**Comment by vycdev** [comment]
> @vycdev Is this PR too large?

Sorry I haven't really had a chance to look at this yet. From what I see at a first glance, you've done a lot of amazing work, so I look forward to testing this.

I'm gonna try to review it in the upcoming days, but it should be fine even if it's big.  

Edit: If you think this is not ready for review yet, you can tell me, since I see this is still a draft.

**Comment by Bjohnson131** [comment]
@vycdev  I'll ping you when it's ready- probably in 1-2 days. I'm going through with a fine-tooth comb right now.

**Comment by vycdev** [comment]
@Bjohnson131 

I was thinking about improving or adding new algorithms for auto-paint, do you think that would collide with this pull request? It matters if this is either simply a separate algorithm, or if its another step in the pipeline and integrates nicely with current algorithms while allowing them to be modified or new ones to be added without affecting this feature.

I was also wondering if number 4, Reducing Height Cliffs Between Columns, would've been better suited as a separate pull request of it it's deeply tied with the multi head printing feature.

I'm also interested how you made the graphs, because they look great and I think they can be used in the docs.

And I'm curious if your 3d printer swaps filament on the parked nozzles, aka the non active ones while it's printing. At least that's what I am assuming.

**Comment by Bjohnson131** [comment]
> I was thinking about improving or adding new algorithms for auto-paint, do you think that would collide with this pull request? It matters if this is either simply a separate algorithm, or if its another step in the pipeline and integrates nicely with current algorithms while allowing them to be modified or new ones to be added without affecting this feature.

It may, but not in a large way- the architecture of MPH is as a post-processor. It takes what auto-paint provides, and re-arranges things, creates windows, etc.  The only real breaking thing would be if the data structures were fundamentally altered heavily.


> I was also wondering if number 4, Reducing Height Cliffs Between Columns, would've been better suited as a separate pull request of it it's deeply tied with the multi head printing feature.

I can pull that out- spatial variance optimization is a beast of its own.


> I'm also interested how you made the graphs, because they look great and I think they can be used in the docs.

I used python to make SVGs, and then converted them to pngs. Here's the script I used for spatial vairance: https://gist.github.com/Bjohnson131/b38f134125de0af37ef3537de6a125f1
I'll upload the rest later, along with the SVGs, I'd love to use them in the docs.


> And I'm curious if your 3d printer swaps filament on the parked nozzles, aka the non active ones while it's printing. At least that's what I am assuming.

It does. TBH I hadn't considered doing this at all. right now, the .3mf file inserts gcode 'pause' commands every time filaments need to be swapped out, and then the user is supposed to go and change all the filaments according to the schedule. I hadn't considered a 'hot-swap' design... I'm sure that would be a lot faster, and more convenient to many, but right now that's not how it works. Would 100% be a good followup feature though.

**Comment by vycdev** [comment]
tests/multiHeadAnalysisColorFirst.test.ts contains an extra closing }); at line 659. This causes npm test, npm run build, and npm run lint to fail with TypeScript parse error TS1128. Please remove it so the new multi-head test module runs.

**Comment by vycdev** [comment]
Non-blocking follow-up: Smooth meshing is not safe for a layer that has been partitioned into multiple colours. Each colour mask is passed separately to generateSmoothMesh, so both sides of a shared colour boundary are independently smoothed inward. This leaves the visible gaps shown in the preview and is present in the generated geometry, not just its shading.

I created a follow up issue for this https://github.com/vycdev/Kromacut/issues/40

image

**Comment by vycdev** [comment]
Multi-head analysis runs synchronously from the Build handler, so larger head/palette configurations freeze the UI. The Search depth selector currently has no effect: it is stored and rendered but never reaches the solver.

Please move the multi-head analysis off the main thread and make Fast, Balanced, and Thorough control a real bounded or sampled search strategy.

**Comment by vycdev** [comment]
Multi-head Printing was added to DOC_NAV_GROUPS, but the matching source page, src/docs/multi-head-printing.md, is not included. The docs UI silently filters that unresolved slug out, so the feature has no in-app documentation despite the new diagrams and navigation entry.

Please add the documentation page.

**Comment by vycdev** [comment]
Multi-head settings are not persisted to kromacut.autopaint.v1. After enabling Multi-head mode, changing Head count/Search depth, and reloading the app, the settings reset to their defaults (off, 4, Balanced).

Please include multiHeadMode, multiHeadCount, and multiHeadSearchDepth in the existing storage load/save payload, with backwards-compatible defaults for older saved data.

**Comment by Bjohnson131** [comment]
> Non-blocking follow-up: Smooth meshing is not safe for a layer that has been partitioned into multiple colours. Each colour mask is passed separately to generateSmoothMesh, so both sides of a shared colour boundary are independently smoothed inward. This leaves the visible gaps shown in the preview and is present in the generated geometry, not just its shading.

IMO this should be fixed before merging- I'll have some time tn to take a closer look.

**Comment by Bjohnson131** [comment]
Ive got a fix for all but the smooth meshing.

And let me say: i really need smooth meshing. Im doing my test prints, and it appears that filling in singular pixels is very difficult for the printer to do:





Of course im printing at both the smallest pixel pitch as well as smallest layer height- just to make sure things work well at easier settings.

**Comment by vycdev** [comment]
Hm, that doesn't look right, are you sure it's not also a problem with your printer/filament? It looks like the nozzle is digging too much into the print, and there's also lots of stringing

**Comment by Bjohnson131** [comment]
@vycdev  This is ready for re-review. the smooth meshing works a LOT better now :)

**Comment by vycdev** [comment]
Thanks for the updates. I re-reviewed current head `6b194f9`. The smooth meshing/export work looks much healthier now, and `npm test` plus `npm run build` both pass.

Remaining items I found:

1. `npm run lint` still fails.

`src/hooks/useSwapPlan.ts:132` includes `multiHeadWindows` in the first `useMemo` dependency list even though that memo does not read it. Because lint runs with `--max-warnings=0`, this warning blocks CI.

2. Multi-head print instructions can disappear after remount.

`ThreeDControls` initializes local `multiHeadWindows` to `[]`, then passes that local value into `useSwapPlan`, while the other schedule inputs come from `persisted`. After building, switching away from 3D and back can leave `multiHeadPlan` null even though the built/persisted state still has the schedule data.

Also, `PrintInstructions` has a `multiHeadMode` fallback message, but `ThreeDControls` never passes `multiHeadMode`, so the UI can fall back to single-head instructions instead of showing the multi-head “build schedule” state.

3. The multi-head docs page is still missing.

`DocsPage.tsx` references the `multi-head-printing` slug, but there is no `src/docs/multi-head-printing.md`. Since docs are bundled from actual Markdown files and missing slugs are filtered out, the new feature still has no in-app docs page.

4. `useMultiHeadWorker` should clean up on unmount.

The hook terminates the worker when a new run starts or when the worker responds, but it does not have an unmount cleanup effect. If the user leaves the 3D panel while analysis is running, the worker can continue running and then try to update state after unmount.

**Comment by vycdev** [comment]
Thanks for the updates. I re-reviewed current head `64b2107` and also simulated merging it with the current `develop` branch, since this PR is now 22 commits behind it.

The earlier lint issue, settings persistence, remount/instruction state, and worker cleanup findings are fixed. The simulated merged tree also passes `npm test` (495/495), `npm run lint`, and `npm run build`.

I found the following remaining items before this is ready to merge:

1. The multi-head optical model scales hiding distance a second time.

Kromacut profile schema v2 stores frontlit hiding distance directly in `filament.td`, but `multiHeadAnalysis.ts`, `multiHeadAnalysisColorFirst.ts`, and `patchedLayersToPlan.ts` repeatedly multiply it by `0.1`. For example, a stored HD of `0.71 mm` is evaluated as `0.071 mm`, making layers appear much more opaque than the standard auto-paint pipeline. This affects color scoring, window selection, previews, and ultimately the physical head assignments. The multi-head path also drops calibrated per-channel HD values.

Please consume stored HD directly and use the shared `channelHds()` / `filamentTdChannels` model so multi-head scoring matches normal auto-paint.

2. An empty or failed analysis still produces a multi-head export without a valid schedule.

When no improving windows are found, `runMultiHeadLayerAnalysisColorFirst` returns the empty result. `ThreeDControls` still persists `multiHeadMode: true`, and `App` therefore passes `extruderCount` to the exporter even though there are no nozzle-tagged meshes or swap events. `export3mf` then falls back to `materialIndex + 1` and clamps that value to the head count, which can silently assign layers to the wrong heads. A worker error follows effectively the same silent fallback path because the exposed worker error is not rendered or used to stop the build.

Please either build a complete non-windowed head schedule/nozzle mapping for this case, or abort/fall back explicitly and tell the user that multi-head analysis did not produce a usable plan. It should not emit a multi-head 3MF with guessed assignments.

3. Flat Paint and Multi-head mode can currently be enabled together without a compatible schedule.

The Flat Paint geometry path ignores the multi-head nozzle assignments, while export still enables the N-head configuration and uses the schedule calculated for the normal stepped stack. If there are more Flat Paint filament objects than heads, later objects are clamped onto the same head. These modes should be mutually exclusive for now, unless a Flat Paint-specific head assignment and swap schedule is implemented.

4. Search depth is still exhaustive and the UI labels do not match the implementation.

Every tier evaluates all `K^N` combinations in `findConsensusCombo` and again in the per-color assignment pass. "Fast (coarse sampling)" does not sample combinations, and "Thorough (all pixel groups)" uses the same pixel groups as the other tiers; the current setting only changes the improvement threshold and maximum number of selected-window iterations. The head-count input also has no upper bound. Eight heads can already require `8^8 = 16,777,216` combinations per candidate window, before the second exhaustive pass and nozzle-assignment DP.

Please add a deterministic combination budget/sampling strategy or enforce a safe tested head-count limit, and align the option labels with the behavior.

5. The multi-head documentation page is still missing.

`DocsPage.tsx` references `multi-head-printing`, but `src/docs/multi-head-printing.md` does not exist, so the entry is silently filtered out. This major feature also needs an unreleased changelog entry. The PR description should be updated as well: it still describes removed/stale behavior such as spatial variance and the old frontlit `x0.1` conversion, and should document the matching N-nozzle OrcaSlicer profile and manual pause requirements.

The implementation and test coverage have improved substantially, but I would keep this open until the optical-model and export-safety issues above are addressed.
